import './globals.css'
import Link from 'next/link'
export const metadata = {
  title: 'nextDemo',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  console.log(Object.keys(props))
  const { children, auth } = props
  return (
    <html lang="en">
      <body >
        <div><Link href={'/'}>Go To Home</Link></div>
        {children}
        {auth}
      </body>

    </html>
  )
}
